### ISSUE TITLE
Using host mounted directory for /logs prevents Neo4j startup with permission error

### ISSUE THREAD

**Issue by mjmare** [neo4j/docker-neo4j#131]
This fails:
```
docker run -it -e NEO4J_AUTH=none --network=host -v /vol/logs:/logs neo4j:3.3
```
this succeeds:
```
docker run -it -e NEO4J_AUTH=none --network=host -v /vol/data:/data neo4j:3.3
```

Error message:
```
# docker run -it -e NEO4J_AUTH=none --network=host -v /vol/logs:/logs --privileged neo4j:3.3
Active database: graph.db
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2018-04-03 21:52:02.914+0000 WARN  Unknown config option: causal_clustering.discovery_listen_address
2018-04-03 21:52:02.925+0000 WARN  Unknown config option: causal_clustering.raft_advertised_address
2018-04-03 21:52:02.926+0000 WARN  Unknown config option: causal_clustering.raft_listen_address
2018-04-03 21:52:02.927+0000 WARN  Unknown config option: ha.host.coordination
2018-04-03 21:52:02.929+0000 WARN  Unknown config option: causal_clustering.transaction_advertised_address
2018-04-03 21:52:02.930+0000 WARN  Unknown config option: causal_clustering.discovery_advertised_address
2018-04-03 21:52:02.934+0000 WARN  Unknown config option: ha.host.data
2018-04-03 21:52:02.934+0000 WARN  Unknown config option: causal_clustering.transaction_listen_address
2018-04-03 21:52:03.030+0000 INFO  ======== Neo4j 3.3.4 ========
2018-04-03 21:52:03.230+0000 INFO  Starting...
2018-04-03 21:52:03.380+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2fd66ad3' was successfully initialized, but failed to start. Please see the attached cause exception "/logs/debug.log (Permission denied)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2fd66ad3' was successfully initialized, but failed to start. Please see the attached cause exception "/logs/debug.log (Permission denied)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2fd66ad3' was successfully initialized, but failed to start. Please see the attached cause exception "/logs/debug.log (Permission denied)".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:220)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2fd66ad3' was successfully initialized, but failed to start. Please see the attached cause exception "/logs/debug.log (Permission denied)".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:212)
        ... 3 more
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /logs/debug.log (Permission denied)
        at org.neo4j.kernel.impl.factory.PlatformModule.createLogService(PlatformModule.java:301)
        at org.neo4j.kernel.impl.factory.PlatformModule.<init>(PlatformModule.java:161)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.createPlatform(GraphDatabaseFacadeFactory.java:244)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:158)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
Caused by: java.io.FileNotFoundException: /logs/debug.log (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at org.neo4j.io.fs.DefaultFileSystemAbstraction.openAsOutputStream(DefaultFileSystemAbstraction.java:76)
        at org.neo4j.io.file.Files.createOrOpenAsOuputStream(Files.java:51)
        at org.neo4j.logging.RotatingFileOutputStreamSupplier.openOutputFile(RotatingFileOutputStreamSupplier.java:336)
        at org.neo4j.logging.RotatingFileOutputStreamSupplier.<init>(RotatingFileOutputStreamSupplier.java:135)
        at org.neo4j.logging.RotatingFileOutputStreamSupplier.<init>(RotatingFileOutputStreamSupplier.java:119)
        at org.neo4j.kernel.impl.logging.StoreLogService.<init>(StoreLogService.java:180)
        at org.neo4j.kernel.impl.logging.StoreLogService.<init>(StoreLogService.java:44)
        at org.neo4j.kernel.impl.logging.StoreLogService$Builder.build(StoreLogService.java:124)
        at org.neo4j.kernel.impl.factory.PlatformModule.createLogService(PlatformModule.java:297)
        ... 12 more
2018-04-03 21:52:03.400+0000 INFO  Neo4j Server shutdown initiated by request

```

**Comment by beho** [comment]
Same problem when attempting to upgrade from  3.3.3 to 3.3.4.

Using following command:

```
docker run \
  --publish=7474:7474 \
  --publish=7687:7687 \
  --volume=/home/project/conf:/conf \
  --volume=/home/project/data:/data \
  --volume=/home/project/logs:/logs \
  neo4j:3.3.X
```

**Comment by tommymessbauer** [comment]
When upgrading to 3.3.5, I had to remove the logs mount from docker-compose. I made no other changes and things worked as expected.

Before:
```
neo4j:
    image: "neo4j:3.3.5"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
```

After: 
```
neo4j:
    image: "neo4j:3.3.5"
    volumes:
      - neo4j_data:/data
```

**Comment by alanbchristie** [comment]
Had the same problem building from `3.3.5` in OpenShift (with and without external volumes). I can't say anything for `3.3.4` because I just moved back to the image that was previously working for me, which is `3.3.3`. I'll stay with `3.3.3` for now.

**Comment by mjmare** [comment]
With 3.3.5 I even had the problem with the data volume, rendering the docker image useless...
3.3.3 is the last one that worked for me.

**Comment by rflauer** [comment]
Problem still showing up for 3.4.0

**Comment by praveenag** [comment]
@OleMussmann @lilianaziolek Recently we have made changes to Dockerfile to make sure neo4j running in docker is run as user `neo4j` instead of `root` for security reasons. see [neo4j issue](https://github.com/neo4j/docker-neo4j/issues/50)

We suggest that you specify which user to run as by invoking docker with the `--user` argument as suggested in the docs [here](https://neo4j.com/docs/operations-manual/current/installation/docker/#docker-user)

**Comment by lilianaziolek** [comment]
@praveenag I don't understand why you closed this issue. Your documentation is incorrect. Neither of the options (with or without the user parameter) provided actually starts the process.

**Comment by bsccrod** [comment]
I agree with @lilianaziolek, this issue should not be closed.  I am running on CentOs, and attempting to start a new 3.4.0 container, utilizing the --user flag; however, it appears to have no effect.  I still get the Permissions Denied error.  The only work-around I've found is to open read/write permissions on the log directory to 'Everyone', though it then leads me to a NULL exception error, which Enterprise Support is trying to track down.  Regardless, the --user argument does not appear to be working correctly.

**Comment by dhimmel** [comment]
I am getting `/logs/debug.log (Permission denied)` when running the `neo4j:3.2.12-enterprise` Docker. I did not have this problem with `neo4j:3.2.3-enterprise`. Does anyone know which minor version of 3.2 this bug was introduced, so I can upgrade until that point?

My docker run command is ([source](https://github.com/dhimmel/hetionet/tree/6d26d15e9055b33b4fd97a180fa288e4f2060b96/hetnet/neo4j/docker#running-the-docker)):

```sh
docker run \
  --name=hetionet-container \
  --rm \
  --publish=7474:7474 \
  --publish=7687:7687 \
  --volume=$HOME/neo4j/hetionet-data:/data \
  --volume=$HOME/neo4j/hetionet-logs:/logs \
  dhimmel/hetionet
```

Sounds like there is still no workaround for users that require logs to be accessible by a volume?

**Comment by lilianaziolek** [comment]
@bsccrod did you try the workaround mentioned by Ole a bit further up this thread? it worked for me and doesn't require opening the directory to everybody.

**Comment by bsccrod** [comment]
@lilianaziolek - After we got past the Permission Denied issue (using the Everyone setting), we hit the NULL exception error, which we're working on with Support.  So we were waiting to hear back on that, before re-addressing the Permission issues.  That said, I'll give that one a shot now, and see if that fixes both the Permissions AND the NULL exception.  I'll let you know.

**Comment by bsccrod** [comment]
@lilianaziolek We're running CentOS, which, it turns out, does not compile systemd with the timesync feature (nor user/group).  Yes, we could "create" such a user (or more specifically the desired uid:gid), but I'd rather not have to create arbitrary users/groups on the system, in order to make this work.

**Comment by lilianaziolek** [comment]
@bsccrod Ouch, sounds like even more problems! I've only tested that on a plain Ubuntu VM - looks like CentOS is a very different beast (I've not had any exposure to it so far). I hope you get the help you need from Neo4j folks :)

**Comment by bsccrod** [comment]
All - I've found another work-around that works in our environment without requiring ANY permission or ownership changes; although, the Neo4j image does make one of its own changes, which I'm not happy about, but can live with (for now).

The keys for us were to bypass the default logfile mapping, and to specify our Environment settings via Docker -e flags, thus not requiring the /conf mapping.

Instead of mapping our local logs folder to the container's /logs folder, we mapped it to a custom folder:  
--volume [local path]/logs:/neologs

We then set the environment setting for NEO4J_dbms_logs_debug_path:
-e NEO4J_dbms_logs_debug_path=/neologs/debug.log

With the additional docker flag (NOTE:  the logged in user is the owner of the host's mapped folders)
--user="$(id -u):$(id -g)"

We have a successful launch of version 3.4.1 (and a successful upgrade from 3.2.2).

My only complaint beyond the default logfile mapping not working properly, is that the Docker container CHANGES the ownership of the /data folder to be neo4j:neo4j.  I dislike this because that uid:gid combination (i.e. 100:101) is INVALID on the host system.  We still have access to the /data folder via root; however, not with the originally logged in user account. 

I think this is a bad practice, but again, not catastrophic in our environment.

**Comment by lilianaziolek** [comment]
@bsccrod Nice trick! 
Wouldn't the same approach work for the data directory, so that you could have your owner set for this directory? IIRC you can set data dir location in conf file, and I expect the docker image only touches whatever is mounted as /data.

**Comment by bsccrod** [comment]
@lilianaziolek Nice catch!  I just tried it, and sure enough, simply bypassing the default mapping for the /data directory did the trick.  The container no longer changes the ownership.  

For reference, I used:

--volume /usr/neo4j/data:/neodata
-e NEO4J_dbms_directories_data=/neodata

**Comment by praveenag** [comment]
@lilianaziolek For my diagnosis, Could you please confirm 
a) You are working on a *Nix environment 
b) the logs and data directory that you are passing are accessible by the user you are passing along using `--user` option
c) `--user` that you pass along is *not* root user

**Comment by mjmare** [comment]
@bsccrod Excellent workaround!  Especially when using docker-compose which does not provide a way to supply the user.

**Comment by mjmare** [comment]
@praveenag Why was this issue closed? A workaround is not a solution, obviously. 
At the very least update the documentation with instructions on how to properly use the image. 
It is not obvious at all how one would go about using this image with Docker-compose and Docker swarm where setting the user is not possible.

**Comment by OleMussmann** [comment]
The workaround from @bsccrod - setting `NEO4J_dbms_logs_debug_path` - does not work for me for version 3.4.5. The official documentation is still wrong. I can have an external `data` folder, but I cannot expose `config` or `logs`.

This issue is still ongoing.

Why is the interface changing so much? We have to tweak our scripts continuously to keep up with the developments here. Whack-a-mole. Please don't break userspace on a regular basis. If it's really necessary, **please document it well**.

**Comment by jennyowen** [comment]
This should now be fixed in our dockerfile with:
https://github.com/neo4j/docker-neo4j/pull/161

It looks like logs of people were suffering from this. Sorry about that. I fixed the docker entrypoint for releases all the way back to 3.1, and the fix will be picked up when we release new patches.

**Comment by jennyowen** [comment]
If we automatically `chown`/`chmod` the mounted folders, it works but compromises the security of the mounted folder(s):
#165 
#164 
#130 

If we leave file permissions alone, then the user has to take care of making the mounted folder writable to whatever user is inside the container. This is tricky and not ideal, especially if you're just beginning with docker. It might be the correct thing to do, but leads to all the problems people have encountered in this issue.

In my opinion the best way to run the Neo4j container is:
```
docker run \ 
docker run \
  --user="$(id -u)":"$(id -g)" \
  --publish=7474:7474 \
  --publish=7687:7687 \
  --volume=$HOME/data:/data \
  --volume=$HOME/logs:/logs \
```
The line `--user="$(id -u)":"$(id -g)"` tells docker to run the container as the current user. As long as the current user has access to the mounted folders, it should work.

See also:
https://github.com/neo4j/docker-neo4j/issues/130#issuecomment-474341337

I think I need to write some documentation about this and why it works.

**Comment by lilianaziolek** [comment]
@jennyowen I agree about not touching the permissions of existing folders, but the issue I was encountering was happening when the folders were created (i.e. they didn't exist before me running docker run). If the image does something for the user (creates the folders), it should do it properly. So, either fail immediately and force user the create folders with correct permissions upfront (IMO not super user friendly, but possible), OR create the folders correctly. Situation encountered was the worst of both worlds.
And, of course, fully up-to-date docs would also help :) The way it was back when this issue was created (not sure now) if you simply copy-pasted the command from docs, things would not work.

**Comment by jennyowen** [comment]
@lilianaziolek  I assume by "create the folders correctly" you mean that it creates a new folder that the container can just write to?

When you mount a volume to a folder that doesn't exist, *docker* creates the folder before invoking any of our code within the image. So there's not so much we can do to create the folder correctly, because from inside the container there's no way of knowing if the folder is new or not.

https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only


> if you simply copy-pasted the command from docs, things would not work

Yeah, that's fixed at least.

**Comment by lilianaziolek** [comment]
@jennyowen Gotcha, I wasn't sure if it was docker itself or the image code that creates the directories. In this case indeed I can see how that you can't safely "correct" the permissions.
Is there a way you can check in the container, before launching Neo4j, that the permissions are sufficient and, if not, fail immediately saying exactly what permissions need to be set and on which directories? This would, at least, help people who somehow managed to mess up their setup/permissions/user parameters and/or didn't reach the right point in the docs.

**Comment by jennyowen** [comment]
@lilianaziolek That's what I want to do, yes :slightly_smiling_face: 

Sadly the current documentation promises that you can just mount volumes and it'll just work, so our code needs to do some permissions fudging for now. Hopefully I can fix the permissions and error reporting for the next minor release though.

**Comment by joeshifteight** [comment]
Anyone else hitting this error with 3.5.6?

**Comment by jennyowen** [comment]
@joeshifteight it should be fixed in 3.5.6. Can you create a new issue?

**Comment by mitasov-ra** [comment]
This error still reproduces in 5.3.0. A workaround with setting custom user `--user="$(id -u):$(id -g)"` leads to another error:

```
Folder /conf is not accessible for user: N or group N or groups N, this is commonly a file permissions issue on the mounted folder.
```

**Comment by MikhailGordeev** [comment]
> This error still reproduces in 5.3.0. A workaround with setting custom user `--user="$(id -u):$(id -g)"` leads to another error:
> 
> ```
> Folder /conf is not accessible for user: N or group N or groups N, this is commonly a file permissions issue on the mounted folder.
> ```

The same is here in version 5.7.0. Did you find a solution?

**Comment by sammy-alaniz** [comment]
I still have this issue
