### ISSUE TITLE
Container started but i cannot `neo4j start`

### ISSUE THREAD

**Issue by navidarry** [neo4j/docker-neo4j#199]
HI
I pulled neo4j:latest image. and create and start a container with this command successfully:

```
> docker create \
> --name myneo4j \
> -p7688:7688  \
> -v $HOME/neo4j/data:/data \
> -v $HOME/neo4j/logs:/logs \
> -v $HOME/neo4j/plugins:/plugins \
> -v $HOME/neo4j/import:/var/lib/neo4j/import  \
> --env NEO4J_AUTH=neo4j/test \
>  neo4j:latest

aeb03348cf1bab0d487e250e505add56b4785c632f6560abdd701bfcfcead8fb


> docker start myneo4j
myneo4j

> docker exec -it myneo4j bash neo4j start
```

here is the neo4j.log file:

```
nohup: ignoring input
2019-10-02 16:43:40.835+0000 INFO  ======== Neo4j 3.5.11 ========
2019-10-02 16:43:40.852+0000 INFO  Starting...
2019-10-02 16:43:41.936+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6239aba6' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6239aba6' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6239aba6' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:45)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:124)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@6239aba6' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:180)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory, /data/databases
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:232)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:148)
	at org.neo4j.server.database.CommunityGraphFactory.newGraphDatabase(CommunityGraphFactory.java:41)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:90)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@1984b1f' was successfully initialized, but failed to start. Please see the attached cause exception "Store and its lock file has been locked by another process: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:473)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
	at org.neo4j.graphdb.facade.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:227)
	... 9 more
Caused by: org.neo4j.kernel.StoreLockException: Store and its lock file has been locked by another process: /data/databases/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
	at org.neo4j.kernel.internal.locker.StoreLocker.storeLockException(StoreLocker.java:116)
	at org.neo4j.kernel.internal.locker.StoreLocker.checkLock(StoreLocker.java:92)
	at org.neo4j.kernel.internal.locker.GlobalStoreLocker.checkLock(GlobalStoreLocker.java:61)
	at org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:36)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
	... 11 more
2019-10-02 16:43:41.937+0000 INFO  Neo4j Server shutdown initiated by request
```

how solve this issue?
may there is because wrong config?

**Comment by jennyowen** [comment]
This isn't a docker issue, but happens when you have 2 neo4j processes trying to access the same database, Possibly you also could have had a neo4j container shut down badly before it could clear the lock.
https://stackoverflow.com/a/28587386

Since you're mounting a `/data` directory, you probably have another container running with the same data folder mounted to it. Stop all neo4j containers, and if `$HOME/neo4j/data/databases/graph.db/store_lock` still exists when they're shut down then delete it.
