### ISSUE TITLE
Browser Web App is not started

### ISSUE THREAD

**Issue by bonya** [neo4j/docker-neo4j#271]
- Expected behaviour - neo4j browser is started; no error in output
- Actual behaviour - neo4j browser is not started
- Neo4j image tag being used, eg `neo4j:4.1`
- Docker Engine - Community - 19.03.12
- Operating system: Mac OSX 10.15.6

```
(awsdev) ➜  notebooks docker run --rm \
    --name neo4j \
    -e NEO4J_AUTH=neo4j/test \
    -p 7474:7474 \
    -p 7687:7687 \
    -p 7473:7473 \
    -v $PWD/neo4j/data:/data \
    -v $PWD/neo4j/logs:/logs \
    neo4j:4.1
Warning: Folder mounted to "/logs" is not writable from inside container. Changing folder owner to neo4j.
Warning: Folder mounted to "/data" is not writable from inside container. Changing folder owner to neo4j.
Changed password for user 'neo4j'.
Directories in use:
  home:         /var/lib/neo4j
  config:       /var/lib/neo4j/conf
  logs:         /logs
  plugins:      /var/lib/neo4j/plugins
  import:       /var/lib/neo4j/import
  data:         /var/lib/neo4j/data
  certificates: /var/lib/neo4j/certificates
  run:          /var/lib/neo4j/run
Starting Neo4j.
2020-07-31 14:56:34.354+0000 INFO  Starting...
2020-07-31 14:56:36.604+0000 INFO  ======== Neo4j 4.1.1 ========
2020-07-31 14:56:49.381+0000 INFO  Initializing system graph model for component 'security-users' with version -1 and status UNINITIALIZED
2020-07-31 14:56:49.388+0000 INFO  Setting up initial user from `auth.ini` file: neo4j
2020-07-31 14:56:49.390+0000 INFO  Creating new user 'neo4j' (passwordChangeRequired=false, suspended=false)
2020-07-31 14:56:49.397+0000 INFO  Setting version for 'security-users' to 2
2020-07-31 14:56:49.402+0000 INFO  After initialization of system graph model component 'security-users' have version 2 and status CURRENT
2020-07-31 14:56:49.409+0000 INFO  Performing postInitialization step for component 'security-users' with version 2 and status CURRENT
2020-07-31 14:57:04.702+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2020-07-31 14:57:05.651+0000 WARN  Failed startup of context o.e.j.w.WebAppContext@8dbf0f2{/browser,jar:file:/var/lib/neo4j/lib/neo4j-browser-4.1.0.jar!/browser,UNAVAILABLE} Temp dir /tmp/jetty-0_0_0_0-7474-neo4j-browser-4_1_0_jar-_browser-any-10894181717037935465.dir not useable: writeable=false, dir=false
java.lang.IllegalStateException: Temp dir /tmp/jetty-0_0_0_0-7474-neo4j-browser-4_1_0_jar-_browser-any-10894181717037935465.dir not useable: writeable=false, dir=false
	at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory(WebInfConfiguration.java:547)
	at org.eclipse.jetty.webapp.WebInfConfiguration.makeTempDirectory(WebInfConfiguration.java:519)
	at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory(WebInfConfiguration.java:468)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:138)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:407)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.neo4j.server.web.Jetty9WebServer.startJetty(Jetty9WebServer.java:300)
	at org.neo4j.server.web.Jetty9WebServer.start(Jetty9WebServer.java:143)
	at org.neo4j.server.AbstractNeoWebServer.startWebServer(AbstractNeoWebServer.java:283)
	at org.neo4j.server.AbstractNeoWebServer$ServerComponentsLifecycleAdapter.start(AbstractNeoWebServer.java:468)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
	at org.neo4j.server.AbstractNeoWebServer.start(AbstractNeoWebServer.java:181)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:442)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:110)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.startDatabaseServer(DatabaseManagementServiceFactory.java:189)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:158)
	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:117)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:87)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:35)
2020-07-31 14:57:05.724+0000 INFO  Remote interface available at http://localhost:7474/
2020-07-31 14:57:05.730+0000 INFO  Started.
```

**Comment by bonya** [comment]
Was a local issue with my docker space.
