### ISSUE TITLE
Unable to run it on Fedora 23

### ISSUE THREAD

**Issue by 1oglop1** [neo4j/docker-neo4j#37]
Hi, I have recently started experimenting with docker and neo4j, I do not have much knowledge about it now, so you can even suggest me some readings apart from official docs.

I just installed docker and ran the command:

```
docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    neo4j:3.0
```

Can someone please tell me what volume is? I changed my docker folder to another mount point (which works)

But it seems that this image is blocked by selinux (which is far from my knowledge)

here is error which I got:
Then I got warnig by selinux, I used commands to allow the operation then it came again with, write, add_name, create

`Unable to find image 'neo4j:3.0.2' locally
Trying to pull repository docker.io/library/neo4j ... 
3.0.2: Pulling from docker.io/library/neo4j
51f5c6a04d83: Pull complete 
65e9ddd8bd7a: Pull complete 
02500df954bf: Pull complete 
e3b067df5fd6: Pull complete 
121bc2f7d35c: Pull complete 
33b88e5aef8c: Pull complete 
9e022032b28e: Pull complete 
904d018c83c1: Pull complete 
207da73bc483: Pull complete 
bb52553717f4: Pull complete 
Digest: sha256:7123cbc791bcb44085f16d994121d3e84cf3b25a7e984b602e9901765138a2d6
Status: Downloaded newer image for docker.io/neo4j:3.0.2
Starting Neo4j.
2016-06-14 07:44:44.634+0000 INFO  No SSL certificate found, generating a self-signed certificate..
2016-06-14 07:44:45.025+0000 INFO  Starting...
2016-06-14 07:44:45.504+0000 INFO  Bolt enabled on 0.0.0.0:7687.
2016-06-14 07:44:45.596+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@60789398' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@60789398' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@60789398' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:217)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:87)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:66)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@60789398' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:189)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /var/lib/neo4j/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
	at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
	at org.neo4j.server.CommunityNeoServer.lambda$static$31(CommunityNeoServer.java:55)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.StoreLockerLifecycleAdapter@3c913e84' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
	... 10 more
Caused by: org.neo4j.kernel.StoreLockException: Unable to create path for store dir: /var/lib/neo4j/data/databases/graph.db. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)
	at org.neo4j.kernel.internal.StoreLocker.storeLockException(StoreLocker.java:90)
	at org.neo4j.kernel.internal.StoreLocker.checkLock(StoreLocker.java:66)
	at org.neo4j.kernel.internal.StoreLockerLifecycleAdapter.start(StoreLockerLifecycleAdapter.java:40)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
	... 12 more
Caused by: java.io.IOException: Unable to create directory path [/var/lib/neo4j/data/databases/graph.db] for Neo4j store.
	at org.neo4j.io.fs.DefaultFileSystemAbstraction.mkdirs(DefaultFileSystemAbstraction.java:108)
	at org.neo4j.kernel.internal.StoreLocker.checkLock(StoreLocker.java:60)
	... 14 more
`

Warning by selinux

`*****  Plugin catchall (100. confidence) suggests   **************************

If you believe that java should be allowed write access on the data directory by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
-- cmd to run> ausearch -c 'java' --raw | audit2allow -M my-java
-- cmd to run> semodule -X 300 -i my-java.pp

Additional Information:
Source Context                system_u:system_r:svirt_lxc_net_t:s0:c243,c742
Target Context                system_u:object_r:admin_home_t:s0
Target Objects                data [ dir ]
Source                        java
Source Path                   java
Port                          <Unknown>
Host                          oglop-pc
Source RPM Packages           
Target RPM Packages           
Policy RPM                    selinux-policy-3.13.1-158.15.fc23.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Enforcing
Host Name                     oglop-pc
Platform                      Linux oglop-pc 4.4.9-300.fc23.x86_64 #1 SMP Wed
                              May 4 23:56:27 UTC 2016 x86_64 x86_64
Alert Count                   2
First Seen                    2016-06-14 09:44:45 CEST
Last Seen                     2016-06-14 09:44:45 CEST
Local ID                      50904f57-44cf-474d-aa5e-d46ab19388a0

Raw Audit Messages
type=AVC msg=audit(1465890285.586:399): avc:  denied  { write } for  pid=17493 comm="java" name="data" dev="dm-0" ino=1458830 scontext=system_u:system_r:svirt_lxc_net_t:s0:c243,c742 tcontext=system_u:object_r:admin_home_t:s0 tclass=dir permissive=0

Hash: java,svirt_lxc_net_t,admin_home_t,dir,write`

**Comment by 1oglop1** [comment]
Solved by running container in privileged mode

docker run --privileged=true
